feat: add profile for dependant & select list component
code4romania/stam-acasa pull request #178
Opened 2020-04-10 06:23 UTC by RaduCStefanescu

### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes #123 

### How has it been tested?

Tested locally.

2020-04-10 07:28 UTC, tudorgergely commented on frontend/src/components/AddMember/index.js
> +    <form className="user-profile-form">
you need to do at least: `onSubmit={e => e.preventDefault()}` otherwise the page will refresh on submit

2020-04-10 07:36 UTC, tudorgergely commented on frontend/src/api/profileApi.js
> +    await api.post("/profile/family", profile);
why not return the result?

2020-04-10 07:37 UTC, tudorgergely commented on frontend/src/api/profileApi.js
> +    await api.post("/profile/family", profile);
also, no need to do async, await since api.post returns a promise anyway

2020-04-10 09:00 UTC, surdu requested changes

2020-04-10 09:00 UTC, surdu commented on frontend/src/components/AddMember/AddMember.scss
> +    align-items: center;
I don't think `align-items` works on non-flex/grid items.

2020-04-10 09:00 UTC, surdu commented on frontend/src/components/AddMember/AddMember.scss
> +    width: 100%;
`width: 100%` is covered by the wildcard selector `*` above

2020-04-10 09:00 UTC, surdu commented on frontend/src/components/AddMember/index.js
> +        <Input
We now have a [number input type](https://taskforce-fe-components.now.sh/?path=/story/input--types) with `min` and `max`

2020-04-10 09:00 UTC, surdu commented on frontend/src/components/AddMember/index.js
> +          type="text"
We have a [`tel` input type](https://taskforce-fe-components.now.sh/?path=/story/input--types)

2020-04-10 09:00 UTC, surdu commented on frontend/src/components/AddMember/index.js
> +      <Button type="button" onClick={nextStepHandler}>
[Unfortunately](https://github.com/code4romania/taskforce-fe-components/issues/149), the `type` prop on our `Button` component is not what you assume :(.

2020-04-10 12:30 UTC, mmircea16 commented on frontend/src/components/AddMember/index.js
> +    relationType: 0,
This should be `relationshipType` as this is the name in the backend

2020-04-11 11:58 UTC, surdu commented on frontend/src/components/AddMember/index.js
> +      <Button type="button" onClick={nextStepHandler}>
```suggestion
      <Button inputType="button" onClick={nextStepHandler}>
```

2020-04-11 14:57 UTC, surdu approved these changes

2020-04-11 14:58 UTC, merged