chore: register link
code4romania/stam-acasa pull request #77
Opened 2020-03-29 13:26 UTC by adascaliteiradu

### What does it fix?
 * Created link to register page
 * Autologin after register

### How has it been tested?

Local environment

2020-03-29 13:29 UTC, trupci submitted a review, later dismissed

2020-03-29 13:35 UTC, surdu requested changes

2020-03-29 13:35 UTC, surdu commented on frontend/src/components/Header/index.js
> +            href={`${environment.registerUrl}?returnUrl=${window.location}register-complete`}
For scalability, I propose to have in the environment a variable called `API_URL`/`api_url` that for now will equal with `http://localhost:5001` and compose the URLs inside the app using it. The base URL is the one that will change most often / based on the environment, not each URL individually.

2020-03-29 14:27 UTC, bvizureanu commented
for the *CI_FrontEnd* check to pass, please merge from `develop`

2020-03-30 18:32 UTC, surdu approved these changes

2020-03-30 18:33 UTC, merged