Add layout for dashboard
code4romania/stam-acasa pull request #93
Opened 2020-04-01 13:11 UTC by maloun96

https://github.com/code4romania/stam-acasa/issues/22

2020-04-01 15:28 UTC, surdu requested changes

2020-04-01 15:28 UTC, surdu commented on frontend/src/components/BaseDashboard/components/DashboardSidebar/index.js
> +      className={classNames(item.className, "dashboardLink")}
```suggestion
      className={[item.className, "dashboardLink"].join(" ")}
```
Are there any advantages using a library for this?

2020-04-01 15:28 UTC, surdu commented on frontend/src/components/BaseDashboard/BaseDashboard.scss
> +    background: url("../../images/search-icon.svg") no-repeat 34px 50%;
Could we use absolute paths for images?

2020-04-01 15:28 UTC, surdu commented on frontend/src/components/BaseDashboard/BaseDashboard.scss
> +    position: absolute;
For the header part I believe it's better to have a flex-box div with 3 children (1 for the logo, 1 for the search and one for the account links) instead of positioning absolute. Please find here a [FlexBox guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

2020-04-01 15:28 UTC, surdu commented on frontend/src/components/BaseDashboard/BaseDashboard.scss
> +    position: fixed;
For the sidebar / main content we could use the [grid sysem](https://bulma.io/documentation/columns/sizes/) available in Bulma in combination with felx-box.

2020-04-01 15:28 UTC, surdu commented on frontend/src/components/BaseDashboard/index.js
> +import { Header as TFHeader } from "@code4ro/taskforce-fe-components";
```suggestion
import { Header } from "@code4ro/taskforce-fe-components";
```
We don't have any naming conflicts here with another Header component

2020-04-02 07:21 UTC, maloun96 commented on frontend/src/components/BaseDashboard/BaseDashboard.scss
> +    background: url("../../images/search-icon.svg") no-repeat 34px 50%;
I guess we need webpack of babel for that.

2020-04-02 19:15 UTC, surdu commented
@maloun96 Please also fix the build errors. Awesome work! 🤘

2020-04-04 21:01 UTC, surdu requested changes

2020-04-04 21:01 UTC, surdu commented on frontend/src/components/BaseDashboard/components/Box/index.js
> +    <div className="box" {...extraProps}>
I don't think is wise to have a separate component just for the CSS class. Putting the `.box` css in the App.scss should suffice.

2020-04-06 07:23 UTC, maloun96 commented
@surdu remove <Box> component, merged develop into current branch. Now should be fine.

2020-04-06 08:04 UTC, surdu approved these changes

2020-04-06 08:06 UTC, merged